name: Retrain Water Forecast Model

permissions:
  contents: write

on:
  schedule:
    - cron: '*/5 * * * *'   # Every 5 minutes
  # workflow_dispatch:       # Also allow manual retraining

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          # Install all dependencies from requirements.txt
          pip install -r requirements.txt

      - name: Run Retraining Script
        run: |
          python retrain_forecast.py

      - name: Commit and Push forecast.json
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git pull --rebase origin main || true  # Pull latest changes safely
          git add forecast.json
          git add requirements.txt
          git commit -m "Automated forecast update [skip ci]" || echo "No changes to commit"
          git push origin main
